SELECT E.ENAME, M.ENAME AS MANAGER, E.MGR FROM EMP E, EMP M WHERE E.MGR = M.EMPNO;
SELECT E.ENAME, M.ENAME AS MANAGER, E.MGR FROM EMP E LEFT JOIN EMP M ON E.MGR = M.EMPNO;

SELECT ENAME, JOB, EMP.DEPTNO, DNAME, LOC FROM EMP, DEPT WHERE EMP.DEPTNO = DEPT.DEPTNO;
SELECT * FROM EMP WHERE COMM IS NOT NULL;
SELECT * FROM EMP WHERE COMM IS NULL;

SELECT * FROM EMP CROSS JOIN DEPT;
SELECT ENAME, MGR, LOC FROM EMP, DEPT;
SELECT ENAME, MGR, LOC FROM EMP NATURAL JOIN DEPT;
SELECT ENAME, DEPTNO, DNAME, LOC FROM EMP NATURAL JOIN DEPT;
SELECT ENAME, MGR, DNAME, LOC FROM EMP JOIN DEPT USING (DEPTNO);
SELECT ENAME, MGR, DNAME, LOC FROM EMP LEFT JOIN DEPT USING (DEPTNO);
SELECT ENAME, MGR, DNAME, LOC FROM EMP RIGHT JOIN DEPT USING (DEPTNO);

CREATE TABLE job_grade 
(Grade_level varchar(2) not null,
lowest_sal number not null,
highest_sal number not null);

INSERT ALL
    INTO job_grade (Grade_level, lowest_sal, highest_sal) VALUES ('A', 0, 1000)
    INTO job_grade (Grade_level, lowest_sal, highest_sal) VALUES ('B', 1001, 2000)
    INTO job_grade (Grade_level, lowest_sal, highest_sal) VALUES ('C', 2001, 3000)
    INTO job_grade (Grade_level, lowest_sal, highest_sal) VALUES ('D', 3001, 4000)
    INTO job_grade (Grade_level, lowest_sal, highest_sal) VALUES ('E', 4001, 5000)
SELECT * FROM DUAL;

SELECT E.ENAME, E.SAL, J.GRADE_LEVEL FROM EMP E JOIN JOB_GRADE J ON E.SAL BETWEEN J.LOWEST_SAL AND J.HIGHEST_SAL;
SELECT E.ENAME, E.SAL, J.GRADE_LEVEL FROM EMP E JOIN JOB_GRADE J ON E.SAL BETWEEN J.LOWEST_SAL AND J.HIGHEST_SAL ORDER BY J.GRADE_LEVEL;

SELECT * FROM EMP CROSS JOIN JOB_GRADE NATURAL JOIN DEPT;

SELECT ENAME, JOB, (CASE JOB 
WHEN 'PRESIDENT' THEN 'GREAT'
WHEN 'MANAGER' THEN 'GOOD'
WHEN 'ANALYST' THEN 'BROOOO!'
WHEN 'SALESMAN' THEN 'HE OK'
ELSE 'MEH' END) AS BARZ FROM EMP;

SELECT ENAME, JOB, TO_CHAR(SAL, '$999,999.99'),
CASE WHEN JOB = 'MANAGER' THEN 'GOOD'
ELSE 'BAD' 
END AS SALLLL FROM EMP;

SELECT ENAME, JOB, TO_CHAR(SAL, '$999,999.99'),
(CASE WHEN SAL > 3000 THEN 'GOOD' ELSE 'BAD' END) FROM EMP;

SELECT ENAME, JOB, DEPTNO, DNAME, LOC, 
(CASE LOC WHEN 'NEW YORK' THEN 'NY'
WHEN 'DALLAS' THEN 'DA'
WHEN 'CHICAGO' THEN 'CH'
ELSE 'BO'
END) AS SHORTY
FROM EMP NATURAL JOIN DEPT;
